#ifndef OSWITCHOBJECT_H__
#define OSWITCHOBJECT_H__

enum
{
	SWITCH_DROPDOWN				= 100000,			// LONG CYCLE
	SWITCH_INHERITNAME		= 100001,			// BOOL
	SWITCH_OBJNAME				= 100002,			// STRING
	SWITCH_REMOTELINK			= 100003			// LINK
};

#endif // OSWITCHOBJECT_H__
