enum
{
	// string table definitions
	IDS_OSWITCHOBJ	= 10000,
	IDS_SWITCH_DROPDOWN,
	IDS_SWITCH_NONE,
	IDS_SWITCH_INHERITNAME,
	IDS_SWITCH_OBJNAME,
	IDS_SWITCH_REMOTELINK,

// End of symbol definition
  _DUMMY_ELEMENT_
};
